// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `allowed_fields`, `apply_transaction`, `apply`, `database_path`, `merge_array`, `merge_statistics`, `object`, `parse`, `read_property`, `set_property`, `source`, `sql`, `summary`, `text`, `valid_media_name`, `validate_setting`, `validate_statistics`, `validate`

Future<String> exportSnapshot({
  required bool includeBookshelves,
  required bool includeReading,
  required bool includeSettings,
}) => RustLib.instance.api.crateApiBackupExportSnapshot(
  includeBookshelves: includeBookshelves,
  includeReading: includeReading,
  includeSettings: includeSettings,
);

Future<String> inspectSnapshot({required String json}) =>
    RustLib.instance.api.crateApiBackupInspectSnapshot(json: json);

/// Both user databases participate in a single SQLite transaction. A dedicated
/// one-connection pool prevents ATTACH from accidentally reaching another pool
/// connection; the normal database guards also serialize existing FRB writers.
Future<String> importSnapshot({
  required String json,
  required bool overwrite,
}) => RustLib.instance.api.crateApiBackupImportSnapshot(
  json: json,
  overwrite: overwrite,
);
